import { assetPath } from "@/lib/site";

export const CAKE_CATEGORIES = ["wedding", "celebration", "bento", "dessert-table"] as const;

export type CakeCategory = (typeof CAKE_CATEGORIES)[number];

export type Cake = {
  /** URL segment; must be unique and kebab-case. */
  readonly slug: string;
  readonly name: string;
  readonly category: CakeCategory;
  /** One line for cards and social previews. */
  readonly tagline: string;
  /** Two or three sentences for the detail page. */
  readonly description: string;
  readonly flavours: readonly string[];
  readonly finishes: readonly string[];
  readonly servings: string;
  /** Guide price in LKR; real quotes are confirmed by conversation. */
  readonly priceFromLkr: number;
  readonly leadTimeDays: number;
  readonly image: {
    readonly src: string;
    readonly alt: string;
    readonly width: number;
    readonly height: number;
  };
  readonly featured: boolean;
};

export const categoryLabels: Record<CakeCategory, string> = {
  wedding: "Wedding tiers",
  celebration: "Celebration cakes",
  bento: "Bento & minis",
  "dessert-table": "Dessert tables",
};

export const categoryBlurbs: Record<CakeCategory, string> = {
  wedding: "Multi-tier centrepieces, tasted and trialled before the day.",
  celebration: "Birthdays, anniversaries and the ordinary Tuesdays worth marking.",
  bento: "Small, fast and hand-painted — for two people or a desk full of them.",
  "dessert-table": "Coordinated spreads of cake, tarts and bakes for a crowd.",
};

/**
 * The studio catalogue.
 *
 * Photography is a placeholder set generated by `scripts/generate-placeholders.mjs`;
 * replacing a `image.src` with a real photograph is the only change needed once
 * the shoot is delivered. Dimensions are intentionally uniform (4:5 portrait) so
 * that swapping in real files cannot shift the grid.
 */
export const cakes: readonly Cake[] = [
  {
    slug: "ivory-cascade",
    name: "Ivory Cascade",
    category: "wedding",
    tagline: "Three tiers of ivory buttercream with a fresh-flower cascade.",
    description:
      "Our most-requested wedding cake. Three tiers finished in a soft ivory buttercream, combed by hand for a fine vertical texture, then dressed with seasonal blooms the morning of the event. Built on a doweled internal structure so it travels safely to the venue.",
    flavours: ["Vanilla bean & raspberry", "Almond & rose", "Dark chocolate & salted caramel"],
    finishes: ["Combed buttercream", "Fresh seasonal florals", "Gold leaf accents"],
    servings: "80 – 100 guests",
    priceFromLkr: 48000,
    leadTimeDays: 42,
    image: {
      src: assetPath("/images/cakes/ivory-cascade.svg"),
      alt: "Three-tier ivory buttercream wedding cake dressed with fresh flowers",
      width: 1200,
      height: 1500,
    },
    featured: true,
  },
  {
    slug: "gilded-fondant-tier",
    name: "Gilded Tier",
    category: "wedding",
    tagline: "Smooth fondant with hand-applied gold leaf and sugar orchids.",
    description:
      "A formal two-tier cake in mirror-smooth fondant, panelled with 24k edible gold leaf and finished with wired sugar orchids made petal by petal. Designed for receptions where the cake is photographed as much as the couple.",
    flavours: ["Vanilla bean & raspberry", "Pistachio & white chocolate"],
    finishes: ["Fondant", "Edible gold leaf", "Sugar orchids"],
    servings: "50 – 70 guests",
    priceFromLkr: 39000,
    leadTimeDays: 35,
    image: {
      src: assetPath("/images/cakes/gilded-fondant-tier.svg"),
      alt: "Two-tier white fondant cake panelled with gold leaf and sugar orchids",
      width: 1200,
      height: 1500,
    },
    featured: true,
  },
  {
    slug: "midnight-ganache",
    name: "Midnight Ganache",
    category: "celebration",
    tagline: "Dark chocolate ganache, sharp edges, a drift of cocoa nibs.",
    description:
      "A single tier of dark chocolate sponge layered with 70% ganache and set to razor-sharp edges. Finished with a drift of caramelised cocoa nibs and a burnished chocolate shard. Rich enough that thin slices go a long way.",
    flavours: ["Dark chocolate & salted caramel", "Chocolate & espresso"],
    finishes: ["Sharp-edge ganache", "Cocoa nib rim", "Tempered chocolate shard"],
    servings: "20 – 25 guests",
    priceFromLkr: 12500,
    leadTimeDays: 7,
    image: {
      src: assetPath("/images/cakes/midnight-ganache.svg"),
      alt: "Single-tier dark chocolate ganache cake with sharp edges and a cocoa nib rim",
      width: 1200,
      height: 1500,
    },
    featured: true,
  },
  {
    slug: "rose-pistachio",
    name: "Rose & Pistachio",
    category: "celebration",
    tagline: "Pistachio sponge, rose buttercream, candied petals.",
    description:
      "Ground pistachio sponge layered with a restrained rose buttercream — perfumed, never soapy. Finished in a blush ombré and scattered with candied rose petals. A quieter cake for anniversaries and afternoon gatherings.",
    flavours: ["Pistachio & rose", "Pistachio & white chocolate"],
    finishes: ["Ombré buttercream", "Candied rose petals", "Chopped pistachio base"],
    servings: "20 – 25 guests",
    priceFromLkr: 13500,
    leadTimeDays: 7,
    image: {
      src: assetPath("/images/cakes/rose-pistachio.svg"),
      alt: "Blush ombré buttercream cake finished with candied rose petals",
      width: 1200,
      height: 1500,
    },
    featured: true,
  },
  {
    slug: "citrus-poppy",
    name: "Citrus & Poppy",
    category: "celebration",
    tagline: "Lime and poppy seed with a torched Italian meringue crown.",
    description:
      "Lime-soaked poppy seed sponge with a sharp curd centre, crowned with Italian meringue torched to order. Bright and light — the cake to serve after a long lunch, and a favourite in Colombo's heat.",
    flavours: ["Lime & poppy seed", "Passionfruit & coconut"],
    finishes: ["Torched meringue", "Citrus zest", "Naked sides"],
    servings: "15 – 20 guests",
    priceFromLkr: 11000,
    leadTimeDays: 7,
    image: {
      src: assetPath("/images/cakes/citrus-poppy.svg"),
      alt: "Citrus and poppy seed cake topped with torched Italian meringue peaks",
      width: 1200,
      height: 1500,
    },
    featured: false,
  },
  {
    slug: "hand-painted-bento",
    name: "Hand-Painted Bento",
    category: "bento",
    tagline: "A four-inch cake in a box, painted while you wait.",
    description:
      "A four-inch cake for two, hand-painted in food colour with a short message or a small illustration. Boxed with two forks. The quickest thing we make and the one most often bought on the way somewhere.",
    flavours: ["Vanilla bean", "Chocolate fudge", "Red velvet"],
    finishes: ["Hand-painted buttercream", "Message in gold", "Gift box & forks"],
    servings: "2 – 4 guests",
    priceFromLkr: 3500,
    leadTimeDays: 3,
    image: {
      src: assetPath("/images/cakes/hand-painted-bento.svg"),
      alt: "Small hand-painted bento cake in an open gift box",
      width: 1200,
      height: 1500,
    },
    featured: true,
  },
  {
    slug: "vanilla-bean-minis",
    name: "Vanilla Bean Minis",
    category: "bento",
    tagline: "Six two-inch cakes, each finished differently.",
    description:
      "A set of six two-inch cakes, each finished in its own way — piped, painted, pressed with dried flowers. Sent as thank-yous, favours and the sort of gift that arrives at an office and disappears by noon.",
    flavours: ["Vanilla bean", "Lemon & elderflower", "Chocolate fudge"],
    finishes: ["Mixed piping", "Pressed dried flowers", "Individual boxes"],
    servings: "6 guests",
    priceFromLkr: 6500,
    leadTimeDays: 5,
    image: {
      src: assetPath("/images/cakes/vanilla-bean-minis.svg"),
      alt: "Six individually decorated mini cakes arranged in a row",
      width: 1200,
      height: 1500,
    },
    featured: false,
  },
  {
    slug: "garden-dessert-table",
    name: "Garden Dessert Table",
    category: "dessert-table",
    tagline: "A cake, tarts, and small bakes styled as one spread.",
    description:
      "A coordinated table built around a centrepiece cake: fruit tarts, choux, brownie bites and macarons in one palette. We style the table on site and take the stands away the next day.",
    flavours: ["Chef's seasonal selection"],
    finishes: ["Styled on site", "Coordinated palette", "Stands & linens included"],
    servings: "60 – 80 guests",
    priceFromLkr: 55000,
    leadTimeDays: 21,
    image: {
      src: assetPath("/images/cakes/garden-dessert-table.svg"),
      alt: "Dessert table styled with a centrepiece cake, tarts and small bakes",
      width: 1200,
      height: 1500,
    },
    featured: true,
  },
  {
    slug: "spiced-fruit-celebration",
    name: "Spiced Fruit",
    category: "dessert-table",
    tagline: "The traditional Sri Lankan rich cake, cut into gift squares.",
    description:
      "Our take on the traditional rich cake: semolina, cashew, chow chow preserve and dark spice, matured for three weeks and cut into squares. Wrapped in glassine and boxed for weddings, Christmas and Avurudu.",
    flavours: ["Traditional Sri Lankan rich cake"],
    finishes: ["Matured three weeks", "Glassine wrapped", "Gift boxes of 12 or 24"],
    servings: "24 – 48 pieces",
    priceFromLkr: 9500,
    leadTimeDays: 28,
    image: {
      src: assetPath("/images/cakes/spiced-fruit-celebration.svg"),
      alt: "Squares of traditional Sri Lankan rich cake wrapped in glassine paper",
      width: 1200,
      height: 1500,
    },
    featured: false,
  },
];

export function getCakeBySlug(slug: string): Cake | undefined {
  return cakes.find((cake) => cake.slug === slug);
}

export function getFeaturedCakes(limit = 6): readonly Cake[] {
  return cakes.filter((cake) => cake.featured).slice(0, limit);
}

export function getCakesByCategory(category: CakeCategory): readonly Cake[] {
  return cakes.filter((cake) => cake.category === category);
}

/** Categories that actually have cakes, in catalogue order — drives the filters. */
export function getPopulatedCategories(): readonly CakeCategory[] {
  return CAKE_CATEGORIES.filter((category) => getCakesByCategory(category).length > 0);
}

export function formatLkr(amount: number): string {
  return new Intl.NumberFormat("en-LK", {
    style: "currency",
    currency: "LKR",
    maximumFractionDigits: 0,
  }).format(amount);
}
